import ephemerisFixture from "../fixtures/ephemeris.json" with { type: "json" };
import ephemerisText from "../fixtures/ephemeris.oem.txt?raw";
import passesFixture from "../fixtures/passes.json" with { type: "json" };
import fixture from "../fixtures/positions.json" with { type: "json" };
import { expect } from "vitest";
import { readElements, type Elements, type GroundPoint, type Pass, type Position, type TrackPoint, type VisibleWindow } from "../src/index.js";

// The Engine's own test support: the Oracle's fixtures and the helpers that
// compare an answer with them. It lives outside `src` because it imports
// vitest and reads the Ephemeris text through Vite's `?raw` specifier,
// neither of which the published code may carry.

/** Skyfield fixtures generated by `oracle/positions.py`. */
export const oracle = fixture;

/** Skyfield Pass fixtures generated by `oracle/passes.py`. */
export const passOracle = passesFixture;

/** The Elements of one fixture set, read from the OMM object the Oracle wrote; the fixture's own records name sets by key. */
export function fixtureElements(key: string): Elements {
  const set = (fixture.elements as Record<string, { omm: unknown } | undefined>)[key];
  if (set === undefined) throw new Error(`The fixture has no Elements set "${key}"`);
  return readElements(set.omm);
}

/**
 * Degrees along the ground between two sub-points, by the haversine formula
 * written out here rather than by the Engine's own: a track's shape is
 * measured against an independent formula, not against the one
 * `ground-track.ts` samples with.
 */
export function haversineDegrees(from: GroundPoint, to: GroundPoint): number {
  const half = (degrees: number) => Math.sin((degrees * Math.PI) / 360) ** 2;
  const latitudes = Math.cos((from.latitude * Math.PI) / 180) * Math.cos((to.latitude * Math.PI) / 180);
  const chord = Math.sqrt(half(to.latitude - from.latitude) + latitudes * half(to.longitude - from.longitude));
  return (2 * Math.asin(Math.min(1, chord)) * 180) / Math.PI;
}

/** The greatest separation between neighbouring points of a track, in degrees: how coarsely its worst stretch is drawn. */
export const worstGapDegrees = (track: readonly TrackPoint[]) =>
  Math.max(...track.slice(1).map((point, index) => haversineDegrees(track[index]!, point)));

const KM_PER_DEGREE = 111.195;

/**
 * Distance in kilometres between two Positions, treating the small
 * latitude, longitude and altitude differences as orthogonal.
 */
export function positionDistanceKm(a: Position, b: Position): number {
  const meanLatitude = ((a.latitude + b.latitude) / 2) * (Math.PI / 180);
  let longitudeDelta = Math.abs(a.longitude - b.longitude);
  if (longitudeDelta > 180) longitudeDelta = 360 - longitudeDelta;
  const north = (a.latitude - b.latitude) * KM_PER_DEGREE;
  const east = longitudeDelta * KM_PER_DEGREE * Math.cos(meanLatitude);
  const up = a.altitude - b.altitude;
  return Math.hypot(north, east, up);
}

/** The simulated Ephemeris, in the format NASA publishes, and Skyfield's Positions and Passes from it, generated by `oracle/ephemeris.py`. */
export const ephemerisOracle = ephemerisFixture;

/** The text of the fixture Ephemeris, in the format NASA publishes. */
export function fixtureEphemerisText(): string {
  return ephemerisText;
}

type ExpectedPass = (typeof passOracle.searches)[number]["passes"][number];

/**
 * The Standard magnitude a fixture search states, as `findPasses` takes it:
 * a number, or absent for a Satellite the field has published none for. The
 * fixture writes that absence as null, and this is the one place the two
 * spellings meet.
 */
export function searchMagnitude(search: { standardMagnitude: number | null }): number | undefined {
  return search.standardMagnitude ?? undefined;
}

/**
 * The Standard magnitude a fixture search states, for a test whose subject
 * needs one. A search for a Satellite the field has published no brightness
 * for states null rather than an estimate, and a test that reads that as a number is
 * asking the wrong search, so this says so rather than propagating it.
 */
export function statedMagnitude(search: { key: string; standardMagnitude: number | null }): number {
  if (search.standardMagnitude === null) throw new Error(`The fixture search ${search.key} states no Standard magnitude`);
  return search.standardMagnitude;
}

/** Seconds between an instant found by the engine and one Skyfield found. */
export const secondsApart = (actual: Date, expected: string) => Math.abs(actual.getTime() - new Date(expected).getTime()) / 1000;

/** How far apart two angles clockwise from north are, in degrees, the short way round. */
export const degreesApart = (actual: number, expected: number) => {
  const difference = Math.abs(actual - expected) % 360;
  return Math.min(difference, 360 - difference);
};

/**
 * Asserts an azimuth agrees with Skyfield's. Near the zenith an azimuth is
 * ill-conditioned, a hair of sky spanning many degrees of it, so the
 * difference is compared as the angular distance it covers: the azimuths of a
 * Pass that goes overhead may differ by tens of degrees and still put the
 * Satellite in the same place.
 */
function expectAzimuthToAgree(actual: number, expected: number, elevation: number, allowance = 0) {
  const apart = degreesApart(actual, expected) * Math.cos((elevation * Math.PI) / 180);
  expect(apart).toBeLessThan(passOracle.tolerance.azimuthDegrees + allowance);
}

/** Asserts a Pass agrees with Skyfield's within the tolerances the Pass fixture states. */
export function expectPassToAgree(pass: Pass, expected: ExpectedPass) {
  const tolerance = passOracle.tolerance;
  expect(secondsApart(pass.rise.at, expected.rise.at)).toBeLessThan(tolerance.timeSeconds);
  expect(secondsApart(pass.culmination.at, expected.culmination.at)).toBeLessThan(tolerance.timeSeconds);
  expect(secondsApart(pass.set.at, expected.set.at)).toBeLessThan(tolerance.timeSeconds);
  expectAzimuthToAgree(pass.rise.azimuth, expected.rise.azimuth, 0);
  expectAzimuthToAgree(pass.culmination.azimuth, expected.culmination.azimuth, pass.culmination.elevation);
  expectAzimuthToAgree(pass.set.azimuth, expected.set.azimuth, 0);
  expect(Math.abs(pass.culmination.elevation - expected.culmination.elevation)).toBeLessThan(tolerance.elevationDegrees);
  expect(Math.abs(pass.culmination.sunAltitude - expected.culmination.sunAltitude)).toBeLessThan(tolerance.sunAltitudeDegrees);
  expect(pass.culmination.sunlit).toBe(expected.culmination.sunlit);
  // A search states a Standard magnitude or, for a Satellite the field has
  // published none for, does not; the Pass's brightness is there or absent
  // to match, and the fixture says which.
  if (expected.culmination.magnitude === null) expect(pass.culmination.magnitude).toBeNull();
  else expect(Math.abs(pass.culmination.magnitude! - expected.culmination.magnitude)).toBeLessThan(tolerance.magnitude);
  expect(pass.visible).toBe(expected.visible);
  expectWindowToAgree(pass.window, expected.window);
}

/** Asserts a Visible window agrees with Skyfield's: both ends with their reasons, and the peak. */
function expectWindowToAgree(window: VisibleWindow | null, expected: ExpectedPass["window"]) {
  if (expected === null) {
    expect(window).toBeNull();
    return;
  }
  const tolerance = passOracle.tolerance;
  expect(window).not.toBeNull();
  for (const end of ["appears", "disappears"] as const) {
    // An end of a window is an instant on the arc, not a place on it: where
    // the two searches put that instant a moment apart, as they do at a
    // grazing shadow crossing, the Satellite has moved on between them.
    const apart = secondsApart(window![end].at, expected[end].at);
    const drift = apart * tolerance.skyDegreesPerSecond;
    expect(apart).toBeLessThan(tolerance.timeSeconds);
    expectAzimuthToAgree(window![end].azimuth, expected[end].azimuth, window![end].elevation, drift);
    expect(Math.abs(window![end].elevation - expected[end].elevation)).toBeLessThan(tolerance.elevationDegrees + drift);
    expect(window![end].reason).toBe(expected[end].reason);
  }
  expect(Math.abs(window!.peak.magnitude - expected.peak.magnitude)).toBeLessThan(tolerance.magnitude);
  expect(secondsApart(window!.peak.at, expected.peak.at)).toBeLessThan(tolerance.timeSeconds);
}
